name: Create GitHub Issue

on:
  workflow_dispatch:
    inputs:
      issue_type:
        description: "Select type of issue to create"
        required: true
        default: "Feature Request"
        options:
          - "Feature Request"
          - "Bug Report"

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v0.6.0
        with:
          cli_version: latest

      - name: Create GitHub Issue
        run: |
          gh issue create --title "New Issue" \
                          --body-file .github/templates/issue.md \
                          --label "$(echo ${{ github.event.inputs.issue_type }} | tr '[:upper:]' '[:lower:]')" \
                          --web
